version: '3'
services:
  parsejson:
    container_name: multiservice-json_parser
    build: parsejson/.
    restart: on-failure
    networks:
      - multiservice
    ports:
      - "8081:8081"

  algorithm:
    container_name: multiservice-algorithm
    build: algorithm/.
    restart: on-failure
    networks:
      - multiservice
    ports:
      - "8082:8082"

  gateway:
    container_name: multiservice-gateway
    build: gateway/.
    restart: on-failure
    networks:
      - multiservice
    ports:
      - "8080:8080"

  nginx:
    container_name: multiservice-nginx
    image: nginx:alpine
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - parsejson
      - algorithm
      - gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/error:/etc/nginx/sites-enabled/default:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - multiservice

networks:
  multiservice: